// Generated by swish-bridge from the SystemPackage module's symbol graph.
// Don't edit: `run bridge` remakes it.
import Foundation
import SwishKit
import SystemPackage

extension Bridge {
    nonisolated(unsafe) static let system: [BridgedType] = [
        BridgedType(
            name: "FilePath", genericParameters: [],
            conformances: ["CustomStringConvertible": [:], "Encodable": [:], "Equatable": [:], "ExpressibleByStringLiteral": [:], "Hashable": [:]],
            associatedTypes: [:],
            parse: nil, literal: { textLiteral(FilePath.self, $0).map { SwiftValue.make($0, as: "FilePath") } },
            members: [
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath()
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .property, name: "length", isStatic: false,
                    parameters: [],
                    returns: .int, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.length
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "components", isStatic: false,
                    parameters: [],
                    returns: .named("FilePath.ComponentView"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.components
                return SwiftValue.make(result, as: "FilePath.ComponentView")
                    }
                ),
                BridgedMember(
                    kind: .setter, name: "components", isStatic: false,
                    parameters: [Parameter(label: nil, name: "newValue", type: .named("FilePath.ComponentView"))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                        receiver.components = try SwiftValue.unbox(FilePath.ComponentView.self, args["newValue"]!)
                        return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [Parameter(label: "stringLiteral", name: "stringLiteral", type: .string)],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath(stringLiteral: try String(swishValue: args["stringLiteral"]!))
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [Parameter(label: nil, name: "string", type: .string)],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath(try String(swishValue: args["string"]!))
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .property, name: "description", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.description
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "debugDescription", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.debugDescription
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "string", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.string
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "isAbsolute", isStatic: false,
                    parameters: [],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.isAbsolute
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "isRelative", isStatic: false,
                    parameters: [],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.isRelative
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "starts", isStatic: false,
                    parameters: [Parameter(label: "with", name: "other", type: .named("FilePath"))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.starts(with: try SwiftValue.unbox(FilePath.self, args["other"]!))
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "ends", isStatic: false,
                    parameters: [Parameter(label: "with", name: "other", type: .named("FilePath"))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.ends(with: try SwiftValue.unbox(FilePath.self, args["other"]!))
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "isEmpty", isStatic: false,
                    parameters: [],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.isEmpty
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removingRoot", isStatic: false,
                    parameters: [],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.removingRoot()
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .property, name: "lastComponent", isStatic: false,
                    parameters: [],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.lastComponent
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removingLastComponent", isStatic: false,
                    parameters: [],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.removingLastComponent()
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeLastComponent", isStatic: false,
                    parameters: [],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: true,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.removeLastComponent()
                return .list([result.swishValue, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .property, name: "extension", isStatic: false,
                    parameters: [],
                    returns: .optional(.string), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.`extension`
                return (result.map { $0.swishValue } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .setter, name: "extension", isStatic: false,
                    parameters: [Parameter(label: nil, name: "newValue", type: .optional(.string))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                        receiver.`extension` = (args["newValue"]! == .nothing ? nil : try String(swishValue: args["newValue"]!))
                        return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .property, name: "stem", isStatic: false,
                    parameters: [],
                    returns: .optional(.string), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.stem
                return (result.map { $0.swishValue } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .property, name: "isLexicallyNormal", isStatic: false,
                    parameters: [],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.isLexicallyNormal
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "lexicallyNormalize", isStatic: false,
                    parameters: [],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                receiver.lexicallyNormalize()
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "lexicallyNormalized", isStatic: false,
                    parameters: [],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.lexicallyNormalized()
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "lexicallyResolving", isStatic: false,
                    parameters: [Parameter(label: nil, name: "subpath", type: .named("FilePath"))],
                    returns: .optional(.named("FilePath")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.lexicallyResolving(try SwiftValue.unbox(FilePath.self, args["subpath"]!))
                return (result.map { SwiftValue.make($0, as: "FilePath") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removePrefix", isStatic: false,
                    parameters: [Parameter(label: nil, name: "prefix", type: .named("FilePath"))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.removePrefix(try SwiftValue.unbox(FilePath.self, args["prefix"]!))
                return .list([result.swishValue, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "append", isStatic: false,
                    parameters: [Parameter(label: nil, name: "component", type: .named("FilePath.Component"))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                receiver.append(try SwiftValue.unbox(FilePath.Component.self, args["component"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "append", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .string)],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                receiver.append(try String(swishValue: args["other"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "appending", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .named("FilePath.Component"))],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.appending(try SwiftValue.unbox(FilePath.Component.self, args["other"]!))
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "appending", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .string)],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.appending(try String(swishValue: args["other"]!))
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "push", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .named("FilePath"))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                receiver.push(try SwiftValue.unbox(FilePath.self, args["other"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "pushing", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .named("FilePath"))],
                    returns: .named("FilePath"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                let result = receiver.pushing(try SwiftValue.unbox(FilePath.self, args["other"]!))
                return SwiftValue.make(result, as: "FilePath")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeAll", isStatic: false,
                    parameters: [Parameter(label: "keepingCapacity", name: "keepingCapacity", type: .bool, defaultValue: .literal(.bool(false)))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                receiver.removeAll(keepingCapacity: try Bool(swishValue: args["keepingCapacity"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "reserveCapacity", isStatic: false,
                    parameters: [Parameter(label: nil, name: "minimumCapacity", type: .int)],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath = try SwiftValue.unbox(FilePath.self, args["self"]!)
                receiver.reserveCapacity(try Int(swishValue: args["minimumCapacity"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath")])
                    }
                ),
            ]
        ),
        BridgedType(
            name: "FilePath.Component", genericParameters: [],
            conformances: ["CustomStringConvertible": [:], "Encodable": [:], "Equatable": [:], "ExpressibleByStringLiteral": [:], "Hashable": [:]],
            associatedTypes: [:],
            parse: { FilePath.Component($0).map { SwiftValue.make($0, as: "FilePath.Component") } }, literal: { textLiteral(FilePath.Component.self, $0).map { SwiftValue.make($0, as: "FilePath.Component") } },
            members: [
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [Parameter(label: "stringLiteral", name: "stringLiteral", type: .string)],
                    returns: .named("FilePath.Component"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath.Component(stringLiteral: try String(swishValue: args["stringLiteral"]!))
                return SwiftValue.make(result, as: "FilePath.Component")
                    }
                ),
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [Parameter(label: nil, name: "string", type: .string)],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath.Component(try String(swishValue: args["string"]!))
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .property, name: "description", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.Component = try SwiftValue.unbox(FilePath.Component.self, args["self"]!)
                let result = receiver.description
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "debugDescription", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.Component = try SwiftValue.unbox(FilePath.Component.self, args["self"]!)
                let result = receiver.debugDescription
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "string", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.Component = try SwiftValue.unbox(FilePath.Component.self, args["self"]!)
                let result = receiver.string
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "extension", isStatic: false,
                    parameters: [],
                    returns: .optional(.string), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.Component = try SwiftValue.unbox(FilePath.Component.self, args["self"]!)
                let result = receiver.`extension`
                return (result.map { $0.swishValue } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .property, name: "stem", isStatic: false,
                    parameters: [],
                    returns: .string, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.Component = try SwiftValue.unbox(FilePath.Component.self, args["self"]!)
                let result = receiver.stem
                return result.swishValue
                    }
                ),
            ]
        ),
        BridgedType(
            name: "FilePath.ComponentView", genericParameters: [],
            conformances: ["Encodable": [:], "Equatable": [:], "Hashable": [:], "Sequence": [:]],
            associatedTypes: ["Element": .named("FilePath.Component")],
            parse: nil, literal: nil,
            members: [
                BridgedMember(
                    kind: .method, name: "map", isStatic: false,
                    parameters: [Parameter(label: nil, name: "transform", type: .functionType([.named("FilePath.Component")], .parameter("T"), throws: true))],
                    returns: .list(.parameter("T")), generics: ["T": []],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.map({ (a0: FilePath.Component) throws -> Value in try bridgeClosure(shell, args["transform"]!)([SwiftValue.make(a0, as: "FilePath.Component")]) })
                return .list(result)
                    }
                ),
                BridgedMember(
                    kind: .property, name: "last", isStatic: false,
                    parameters: [],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.last
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "last", isStatic: false,
                    parameters: [Parameter(label: "where", name: "predicate", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.last(where: { (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["predicate"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "shuffled", isStatic: false,
                    parameters: [],
                    returns: .list(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.shuffled()
                return .list(result.map { SwiftValue.make($0, as: "FilePath.Component") })
                    }
                ),
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [Parameter(label: "repeating", name: "repeatedValue", type: .named("FilePath.Component")), Parameter(label: "count", name: "count", type: .int)],
                    returns: .named("FilePath.ComponentView"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath.ComponentView(repeating: try SwiftValue.unbox(FilePath.Component.self, args["repeatedValue"]!), count: try Int(swishValue: args["count"]!))
                return SwiftValue.make(result, as: "FilePath.ComponentView")
                    }
                ),
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [Parameter(label: nil, name: "elements", type: .someSequence(.named("FilePath.Component")))],
                    returns: .named("FilePath.ComponentView"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath.ComponentView(try bridgeSequence(args["elements"]!).map { try SwiftValue.unbox(FilePath.Component.self, $0) })
                return SwiftValue.make(result, as: "FilePath.ComponentView")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "append", isStatic: false,
                    parameters: [Parameter(label: nil, name: "newElement", type: .named("FilePath.Component"))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.append(try SwiftValue.unbox(FilePath.Component.self, args["newElement"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "append", isStatic: false,
                    parameters: [Parameter(label: "contentsOf", name: "newElements", type: .someSequence(.named("FilePath.Component")))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.append(contentsOf: try bridgeSequence(args["newElements"]!).map { try SwiftValue.unbox(FilePath.Component.self, $0) })
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeFirst", isStatic: false,
                    parameters: [Parameter(label: nil, name: "k", type: .int)],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.removeFirst(try Int(swishValue: args["k"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeFirst", isStatic: false,
                    parameters: [],
                    returns: .named("FilePath.Component"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: true,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.removeFirst()
                return .list([SwiftValue.make(result, as: "FilePath.Component"), SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeAll", isStatic: false,
                    parameters: [Parameter(label: "keepingCapacity", name: "keepCapacity", type: .bool, defaultValue: .literal(.bool(false)))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.removeAll(keepingCapacity: try Bool(swishValue: args["keepCapacity"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "reserveCapacity", isStatic: false,
                    parameters: [Parameter(label: nil, name: "n", type: .int)],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.reserveCapacity(try Int(swishValue: args["n"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "popLast", isStatic: false,
                    parameters: [],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.popLast()
                return .list([(result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing), SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeLast", isStatic: false,
                    parameters: [],
                    returns: .named("FilePath.Component"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: true,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.removeLast()
                return .list([SwiftValue.make(result, as: "FilePath.Component"), SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeLast", isStatic: false,
                    parameters: [Parameter(label: nil, name: "k", type: .int)],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.removeLast(try Int(swishValue: args["k"]!))
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "filter", isStatic: false,
                    parameters: [Parameter(label: nil, name: "isIncluded", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .named("FilePath.ComponentView"), generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.filter({ (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["isIncluded"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return SwiftValue.make(result, as: "FilePath.ComponentView")
                    }
                ),
                BridgedMember(
                    kind: .method, name: "removeAll", isStatic: false,
                    parameters: [Parameter(label: "where", name: "shouldBeRemoved", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                try receiver.removeAll(where: { (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["shouldBeRemoved"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "forEach", isStatic: false,
                    parameters: [Parameter(label: nil, name: "body", type: .functionType([.named("FilePath.Component")], .void, throws: true))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                try receiver.forEach({ (a0: FilePath.Component) throws -> Void in _ = try bridgeClosure(shell, args["body"]!)([SwiftValue.make(a0, as: "FilePath.Component")]) })
                return .nothing
                    }
                ),
                BridgedMember(
                    kind: .method, name: "first", isStatic: false,
                    parameters: [Parameter(label: "where", name: "predicate", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.first(where: { (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["predicate"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "min", isStatic: false,
                    parameters: [Parameter(label: "by", name: "areInIncreasingOrder", type: .functionType([.named("FilePath.Component"), .named("FilePath.Component")], .bool, throws: true))],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.min(by: { (a0: FilePath.Component, a1: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["areInIncreasingOrder"]!)([SwiftValue.make(a0, as: "FilePath.Component"), SwiftValue.make(a1, as: "FilePath.Component")])) })
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "max", isStatic: false,
                    parameters: [Parameter(label: "by", name: "areInIncreasingOrder", type: .functionType([.named("FilePath.Component"), .named("FilePath.Component")], .bool, throws: true))],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.max(by: { (a0: FilePath.Component, a1: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["areInIncreasingOrder"]!)([SwiftValue.make(a0, as: "FilePath.Component"), SwiftValue.make(a1, as: "FilePath.Component")])) })
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "starts", isStatic: false,
                    parameters: [Parameter(label: "with", name: "possiblePrefix", type: .someSequence(.parameter("PossiblePrefix.Element"))), Parameter(label: "by", name: "areEquivalent", type: .functionType([.named("FilePath.Component"), .parameter("PossiblePrefix.Element")], .bool, throws: true))],
                    returns: .bool, generics: ["PossiblePrefix.Element": []],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.starts(with: try bridgeSequence(args["possiblePrefix"]!), by: { (a0: FilePath.Component, a1: Value) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["areEquivalent"]!)([SwiftValue.make(a0, as: "FilePath.Component"), a1])) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "starts", isStatic: false,
                    parameters: [Parameter(label: "with", name: "possiblePrefix", type: .someSequence(.named("FilePath.Component")))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.starts(with: try bridgeSequence(args["possiblePrefix"]!).map { try SwiftValue.unbox(FilePath.Component.self, $0) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "elementsEqual", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .someSequence(.parameter("OtherSequence.Element"))), Parameter(label: "by", name: "areEquivalent", type: .functionType([.named("FilePath.Component"), .parameter("OtherSequence.Element")], .bool, throws: true))],
                    returns: .bool, generics: ["OtherSequence.Element": []],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.elementsEqual(try bridgeSequence(args["other"]!), by: { (a0: FilePath.Component, a1: Value) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["areEquivalent"]!)([SwiftValue.make(a0, as: "FilePath.Component"), a1])) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "elementsEqual", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .someSequence(.named("FilePath.Component")))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.elementsEqual(try bridgeSequence(args["other"]!).map { try SwiftValue.unbox(FilePath.Component.self, $0) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "lexicographicallyPrecedes", isStatic: false,
                    parameters: [Parameter(label: nil, name: "other", type: .someSequence(.named("FilePath.Component"))), Parameter(label: "by", name: "areInIncreasingOrder", type: .functionType([.named("FilePath.Component"), .named("FilePath.Component")], .bool, throws: true))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.lexicographicallyPrecedes(try bridgeSequence(args["other"]!).map { try SwiftValue.unbox(FilePath.Component.self, $0) }, by: { (a0: FilePath.Component, a1: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["areInIncreasingOrder"]!)([SwiftValue.make(a0, as: "FilePath.Component"), SwiftValue.make(a1, as: "FilePath.Component")])) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "contains", isStatic: false,
                    parameters: [Parameter(label: "where", name: "predicate", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.contains(where: { (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["predicate"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "allSatisfy", isStatic: false,
                    parameters: [Parameter(label: nil, name: "predicate", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.allSatisfy({ (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["predicate"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "contains", isStatic: false,
                    parameters: [Parameter(label: nil, name: "element", type: .named("FilePath.Component"))],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.contains(try SwiftValue.unbox(FilePath.Component.self, args["element"]!))
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "reduce", isStatic: false,
                    parameters: [Parameter(label: nil, name: "initialResult", type: .parameter("Result")), Parameter(label: nil, name: "nextPartialResult", type: .functionType([.parameter("Result"), .named("FilePath.Component")], .parameter("Result"), throws: true))],
                    returns: .parameter("Result"), generics: ["Result": []],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.reduce(args["initialResult"]!, { (a0: Value, a1: FilePath.Component) throws -> Value in try bridgeClosure(shell, args["nextPartialResult"]!)([a0, SwiftValue.make(a1, as: "FilePath.Component")]) })
                return result
                    }
                ),
                BridgedMember(
                    kind: .method, name: "flatMap", isStatic: false,
                    parameters: [Parameter(label: nil, name: "transform", type: .functionType([.named("FilePath.Component")], .someSequence(.parameter("SegmentOfResult.Element")), throws: true))],
                    returns: .list(.parameter("SegmentOfResult.Element")), generics: ["SegmentOfResult.Element": []],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.flatMap({ (a0: FilePath.Component) throws -> [Value] in try bridgeSequence(try bridgeClosure(shell, args["transform"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return .list(result)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "compactMap", isStatic: false,
                    parameters: [Parameter(label: nil, name: "transform", type: .functionType([.named("FilePath.Component")], .optional(.parameter("ElementOfResult")), throws: true))],
                    returns: .list(.parameter("ElementOfResult")), generics: ["ElementOfResult": []],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.compactMap({ (a0: FilePath.Component) throws -> Value? in (try bridgeClosure(shell, args["transform"]!)([SwiftValue.make(a0, as: "FilePath.Component")]) == .nothing ? nil : try bridgeClosure(shell, args["transform"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return .list(result)
                    }
                ),
                BridgedMember(
                    kind: .method, name: "sorted", isStatic: false,
                    parameters: [Parameter(label: "by", name: "areInIncreasingOrder", type: .functionType([.named("FilePath.Component"), .named("FilePath.Component")], .bool, throws: true))],
                    returns: .list(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.sorted(by: { (a0: FilePath.Component, a1: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["areInIncreasingOrder"]!)([SwiftValue.make(a0, as: "FilePath.Component"), SwiftValue.make(a1, as: "FilePath.Component")])) })
                return .list(result.map { SwiftValue.make($0, as: "FilePath.Component") })
                    }
                ),
                BridgedMember(
                    kind: .method, name: "trimPrefix", isStatic: false,
                    parameters: [Parameter(label: "while", name: "predicate", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                try receiver.trimPrefix(while: { (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["predicate"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "trimPrefix", isStatic: false,
                    parameters: [Parameter(label: nil, name: "prefix", type: .someSequence(.named("FilePath.Component")))],
                    returns: .void, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: true,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        var receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                receiver.trimPrefix(try bridgeSequence(args["prefix"]!).map { try SwiftValue.unbox(FilePath.Component.self, $0) })
                return .list([.nothing, SwiftValue.make(receiver, as: "FilePath.ComponentView")])
                    }
                ),
                BridgedMember(
                    kind: .method, name: "count", isStatic: false,
                    parameters: [Parameter(label: "where", name: "predicate", type: .functionType([.named("FilePath.Component")], .bool, throws: true))],
                    returns: .int, generics: [:],
                    isThrowing: false, isRethrowing: true, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = try receiver.count(where: { (a0: FilePath.Component) throws -> Bool in try Bool(swishValue: try bridgeClosure(shell, args["predicate"]!)([SwiftValue.make(a0, as: "FilePath.Component")])) })
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .method, name: "randomElement", isStatic: false,
                    parameters: [],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.randomElement()
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .property, name: "isEmpty", isStatic: false,
                    parameters: [],
                    returns: .bool, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.isEmpty
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "first", isStatic: false,
                    parameters: [],
                    returns: .optional(.named("FilePath.Component")), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.first
                return (result.map { SwiftValue.make($0, as: "FilePath.Component") } ?? .nothing)
                    }
                ),
                BridgedMember(
                    kind: .property, name: "underestimatedCount", isStatic: false,
                    parameters: [],
                    returns: .int, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.underestimatedCount
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .property, name: "count", isStatic: false,
                    parameters: [],
                    returns: .int, generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let receiver: FilePath.ComponentView = try SwiftValue.unbox(FilePath.ComponentView.self, args["self"]!)
                let result = receiver.count
                return result.swishValue
                    }
                ),
                BridgedMember(
                    kind: .initializer, name: "init", isStatic: true,
                    parameters: [],
                    returns: .named("FilePath.ComponentView"), generics: [:],
                    isThrowing: false, isRethrowing: false, isMutating: false,
                    discardableResult: false,
                    body: .native { shell, args in
                        _ = shell
                        let result = FilePath.ComponentView()
                return SwiftValue.make(result, as: "FilePath.ComponentView")
                    }
                ),
            ]
        ),
    ]
}
